const serverCommands = [
    { category: "basic-info-sec", command: "Check", desc: "معرفة معلومات شخص" },
    { category: "basic-info-sec", command: "Changename", desc: "تغيير اسم شخص" },
    { category: "basic-info-sec", command: "Findip", desc: "معرفة أيبي لاعب" },
    { category: "basic-info-sec", command: "Findalts", desc: "إظهار جميع شخصيات لاعب معين" },
    { category: "basic-info-sec", command: "Findserial", desc: "معرفة سريال لاعب" },
    { category: "basic-info-sec", command: "resetaccount", desc: "عمل ريستارت لحساب معين" },
    { category: "basic-info-sec", command: "reconnect", desc: "عمل ريكونت للاعب معين" },
    { category: "basic-info-sec", command: "setage", desc: "تغيير عمر لاعب" },
    { category: "basic-info-sec", command: "setdob", desc: "تغيير ميلاد لاعب" },
    { category: "basic-info-sec", command: "setgender", desc: "تغيير جنس لاعب (ولد/بنت)" },
    { category: "basic-info-sec", command: "setheight", desc: "تغيير وزن لاعب" },
    { category: "faction-sec", command: "Showfactions", desc: "رؤية قائمة الفاكشنات" },
    { category: "faction-sec", command: "delfaction", desc: "حذف فاكشن" },
    { category: "faction-sec", command: "Dutyadmin", desc: "تصليح ديوتي فاكشنات" },
    { category: "faction-sec", command: "makefaction", desc: "صنع فاكشن جديد" },
    { category: "faction-sec", command: "renamefaction", desc: "تغيير اسم الفاكشن" },
    { category: "faction-sec", command: "respawnfaction", desc: "رسبنة سيارات فاكشن معين" },
    { category: "faction-sec", command: "rf", desc: "صنع أو حذف راديو لفاكشن" },
    { category: "faction-sec", command: "srd", desc: "إيقاف جميع أجهزة الراديو في المنطقة" },
    { category: "faction-sec", command: "Setintfaction", desc: "وضع بيت في فاكشن" },
    { category: "faction-sec", command: "setvehfaction", desc: "وضع سيارة في فاكشن" },
    { category: "faction-sec", command: "setfactionrank", desc: "رفع رتبة لاعب في فاكشن (بدون دخول)" },
    { category: "faction-sec", command: "setfaction", desc: "دخول فاكشن على شكل لاعب" },
    { category: "faction-sec", command: "setfactionleader", desc: "دخول فاكشن على شكل ليدر" },
    { category: "gates-sec", command: "Nearbygates", desc: "معرفة إيدي الباب" },
    { category: "gates-sec", command: "Delgate", desc: "محو/حذف الباب" },
    { category: "gates-sec", command: "gates", desc: "فتح لوحة الأبواب" },
    { category: "gates-sec", command: "gotogate", desc: "الانتقال لبوابة معينة" },
    { category: "gates-sec", command: "makegeneric", desc: "صناعة الأسوار والأغراض" },
    { category: "int-sec", command: "ints / interiors", desc: "رؤية البيوت الموجودة" },
    { category: "int-sec", command: "setintentrance", desc: "نقل سهم أو بيت" },
    { category: "int-sec", command: "addint", desc: "صنع إنترو (Id - الاسم - سعر - نوع)" },
    { category: "int-sec", command: "Delint", desc: "حذف إنترو" },
    { category: "int-sec", command: "Restoreint / restoreint", desc: "استرجاع إنترو / استرجاع الداخلية إذا حذفت" },
    { category: "int-sec", command: "Nearbyints", desc: "معرفة إيدي البيت" },
    { category: "int-sec", command: "togint", desc: "غلق البيت" },
    { category: "int-sec", command: "Enableallinterios", desc: "جعل جميع البيوت مغلقة" },
    { category: "int-sec", command: "Setintname", desc: "تغيير اسم البيت" },
    { category: "int-sec", command: "getintprice", desc: "معرفة سعر البيت" },
    { category: "int-sec", command: "Setintprice", desc: "تغيير سعر البيت" },
    { category: "int-sec", command: "Getinttype", desc: "معرفة نوع البيت" },
    { category: "int-sec", command: "Setinttype", desc: "تغيير نوع البيت" },
    { category: "int-sec", command: "Setintid", desc: "تغيير شكل البيت" },
    { category: "int-sec", command: "Getintid", desc: "معرفة إيدي شكل البيت من الداخل" },
    { category: "int-sec", command: "reloadint", desc: "عمل ريستارت للداخلية" },
    { category: "int-sec", command: "setint / setinterior", desc: "تغيير الداخلية" },
    { category: "int-sec", command: "removeint [ID]", desc: "حذف الداخلية نهائياً" },
    { category: "int-sec", command: "sellproperty", desc: "بيع منزلك للسيرفر" },
    { category: "int-sec", command: "addatm", desc: "صنع مصرفة (صرافة)" },
    { category: "int-sec", command: "delatm [id]", desc: "حذف مصرفة" },
    { category: "int-sec", command: "Getkey / changelock", desc: "عمل نسخة مفتاح" },
    { category: "shop-sec", command: "Makeshop", desc: "صنع شوب" },
    { category: "shop-sec", command: "Delshop", desc: "حذف شوب" },
    { category: "shop-sec", command: "Nearbyshops", desc: "معرفة إيدي الشوب" },
    { category: "shop-sec", command: "renameshop", desc: "تغيير اسم الشوب" },
    { category: "shop-sec", command: "Delnearbyshops", desc: "حذف البائع الذي بجانبك" },
    { category: "shop-sec", command: "removeshop", desc: "حذف شوب نهائياً" },
    { category: "shop-sec", command: "Reloadshop", desc: "عمل ريستارت لشوب معين" },
    { category: "shop-sec", command: "Moveshop", desc: "نقل بائع" },
    { category: "shop-sec", command: "makefuel", desc: "صنع بائع بنزين" },
    { category: "shop-sec", command: "Nearbyfuels", desc: "معرفة إيدي بائع البنزين" },
    { category: "shop-sec", command: "Delfuel", desc: "حذف بائع البنزين" },
    { category: "shop-sec", command: "Deldancer", desc: "حذف بائع يرقص" },
    { category: "arrows-sec", command: "Adde", desc: "صنع سهم" },
    { category: "arrows-sec", command: "Dele", desc: "حذف السهم" },
    { category: "arrows-sec", command: "Fixnearbye", desc: "إصلاح أو استرجاع السهم" },
    { category: "arrows-sec", command: "nearbye", desc: "معرفة إيدي السهم" },
    { category: "barriers-sec", command: "Rbs", desc: "وضع حاجز" },
    { category: "barriers-sec", command: "Delrb / delrp", desc: "مسح الحاجز" },
    { category: "barriers-sec", command: "delallrbs", desc: "حذف جميع الحواجز" },
    { category: "barriers-sec", command: "Nearbyrbs / Nearbyrb", desc: "معرفة إيدي الحاجز" },
    { category: "atm-sec", command: "addatm", desc: "صنع مصرفة" },
    { category: "atm-sec", command: "delatm [id]", desc: "حذف مصرفة" },
    { category: "marker-sec", command: "mark", desc: "صنع ماركر" },
    { category: "marker-sec", command: "delmark", desc: "حذف ماركر" },
    { category: "ramps-sec", command: "Addramp", desc: "صنع رامب" },
    { category: "ramps-sec", command: "Delramp", desc: "حذف رامب" },
    { category: "ramps-sec", command: "togglee", desc: "تمكين أو تعطيل رامب" },
    { category: "ramps-sec", command: "nearbyramps", desc: "معرفة إيدي رامب" },
    { category: "vehicles-sec", command: "respawnall", desc: "رسبنة جميع السيارات" },
    { category: "vehicles-sec", command: "Aunimpound", desc: "إزالة السيارات من الحجز" },
    { category: "vehicles-sec", command: "Editveh", desc: "تعديل على السيارات" },
    { category: "vehicles-sec", command: "Fixvehs", desc: "تصليح جميع السيارات" },
    { category: "vehicles-sec", command: "Restartvehall", desc: "ريستارت لجميع السيارات" },
    { category: "vehicles-sec", command: "delnearbyvehs", desc: "معرفة السيارات المحذوفة" },
    { category: "vehicles-sec", command: "Delthisveh", desc: "حذف مركبة مؤقتاً" },
    { category: "vehicles-sec", command: "delveh [id]", desc: "حذف سيارة (تكتب مرتين)" },
    { category: "vehicles-sec", command: "removeveh", desc: "حذف السيارة نهائياً من الخادم" },
    { category: "vehicles-sec", command: "restoreveh", desc: "استرجاع سيارة محذوفة" },
    { category: "vehicles-sec", command: "apark", desc: "بارك لسيارة دون ركوبها" },
    { category: "vehicles-sec", command: "settrackingloc", desc: "جهاز التتبع في السيارة" },
    { category: "vehicles-sec", command: "setvehfaction", desc: "جعل سيارة في فاكشن" },
    { category: "vehicles-sec", command: "Setvehplate", desc: "تغيير لوحة السيارة" },
    { category: "vehicles-sec", command: "delupgrade", desc: "إزالة جميع إضافات السيارة" },
    { category: "vehicles-sec", command: "blowveh", desc: "تفجير سيارة (مع إيدي الراكب)" },
    { category: "vehicles-sec", command: "Nearbyvehicles", desc: "إيدهات السيارات حولك" },
    { category: "vehicles-sec", command: "Getkey", desc: "عمل نسخة من مفتاح السيارة" },
    { category: "vehicles-sec", command: "changelock", desc: "تصفير المفاتيح" },
    { category: "vehicles-sec", command: "setvehtint", desc: "إضافة أو إزالة لون السيارة" },
    { category: "vehicles-sec", command: "makecivveh", desc: "صنع سيارة تكسي/باص/ديلفري" },
    { category: "vehicles-sec", command: "veh", desc: "صنع سيارة مؤقتة" },
    { category: "vehicles-sec", command: "getcolor", desc: "معرفة ألوان سيارة معينة" },
    { category: "vehicles-sec", command: "addupgrade", desc: "ترقية سيارة لاعب" },
    { category: "vehicles-sec", command: "setdamageproof", desc: "جعل السيارة مضادة للضرر" },
    { category: "vehicles-sec", command: "setcolor", desc: "تعديل ألوان السيارة" },
    { category: "vehicles-sec", command: "setcarhp", desc: "تعديل صحة السيارة" },
    { category: "vehicles-sec", command: "getvehweight", desc: "معرفة مواصفات السيارة" },
    { category: "vehicles-sec", command: "Vehlib", desc: "معلومات معرض السيارات" },
    { category: "vehicles-sec", command: "srd", desc: "قفل جميع راديو السيارات حولك" },
    { category: "vehicles-sec", command: "setvol", desc: "رفع أو خفض صوت راديو السيارة" },
    { category: "vehicles-sec", command: "Makeveh a a id 0 1 1", desc: "صنع سيارة" },
    { category: "vehicles-sec", command: "makepaynspray", desc: "صنع مكان تصليح سيارات" },
    { category: "respawn-sec", command: "respawnall", desc: "رسبنة جميع السيارات" },
    { category: "respawn-sec", command: "respawndistrict", desc: "رسبون سيارات المنطقة حولك" },
    { category: "respawn-sec", command: "Respawnciv", desc: "رسبنة سيارات الوظائف" },
    { category: "respawn-sec", command: "respawntrucks", desc: "رسبنة جميع الشاحنات" },
    { category: "respawn-sec", command: "restartcarshops", desc: "رسبنة معرض السيارات" },
    { category: "respawn-sec", command: "respawnveh", desc: "رسبنة سيارة" },
    { category: "respawn-sec", command: "respawnfaction", desc: "رسبنة سيارات فاكشن معين" },
    { category: "respawn-sec", command: "apark", desc: "بارك لمركبة دون ركوب" },
    { category: "stealth-sec", command: "hideadmin", desc: "تشغيل شارة بدون ظهور" },
    { category: "stealth-sec", command: "Disappear", desc: "إخفاء نفسك" },
    { category: "stealth-sec", command: "Supervise", desc: "اختفاء جزئي" },
    { category: "stealth-sec", command: "freecam", desc: "تخفي واختراق جدران" },
    { category: "stealth-sec", command: "Fakeme", desc: "ظهور باسم فيك" },
    { category: "items-sec", command: "giveitem", desc: "أخذ غرض معين" },
    { category: "items-sec", command: "delitem", desc: "حذف غرض معين" },
    { category: "items-sec", command: "moveitem", desc: "نقل غرض معين" },
    { category: "items-sec", command: "delnearbyitems", desc: "حذف جميع الأغراض حولك" },
    { category: "items-sec", command: "items / itemlist", desc: "فتح قائمة الغش" },
    { category: "monitoring-sec", command: "watch", desc: "مراقبة شخص وأنت تتحرك" },
    { category: "monitoring-sec", command: "recon", desc: "مراقبة شخص" },
    { category: "monitoring-sec", command: "showinv", desc: "رؤية أغراض الشخص" },
    { category: "monitoring-sec", command: "Bigears", desc: "رؤية شات الخاص للناس" },
    { category: "monitoring-sec", command: "bigearsf", desc: "مراقبة شات الفاكشنات" },
    { category: "weather-sec", command: "srl", desc: "معرفة مستوى المطر" },
    { category: "weather-sec", command: "Sw 1", desc: "تغيير الطقس" },
    { category: "chat-sec", command: "ho", desc: "رسالة في الشات بدون ظهور اسمك" },
    { category: "chat-sec", command: "g", desc: "شات السبورت" },
    { category: "chat-sec", command: "a", desc: "شات الإدمن" },
    { category: "chat-sec", command: "st", desc: "شات الاستف" },
    { category: "chat-sec", command: "ua", desc: "شات المسؤولين" },
    { category: "chat-sec", command: "togooc", desc: "فتح أو قفل شات العام" },
    { category: "chat-sec", command: "occ / ooc", desc: "كتابة في شات العام / التحدث في الشات العام" },
    { category: "chat-sec", command: "w", desc: "تهمس لشخص" },
    { category: "chat-sec", command: "s", desc: "انتبه لي" },
    { category: "chat-sec", command: "district", desc: "تنبيه إطلاق نار" },
    { category: "chat-sec", command: "Clearchat / clearchat", desc: "مسح وتنظيف الشات" },
    { category: "chat-sec", command: "Showhud", desc: "إخفاء محتويات الشاشة" },
    { category: "chat-sec", command: "showchat", desc: "إخفاء/إظهار الشات" },
    { category: "chat-sec", command: "togglef", desc: "قفل شات الوظيفة" },
    { category: "chat-sec", command: "f", desc: "شات الوظيفة" },
    { category: "chat-sec", command: "fl", desc: "شات الليدرات" },
    { category: "chat-sec", command: "hq", desc: "شات عام الوظيفة" },
    { category: "chat-sec", command: "m", desc: "التحدث في الميكرفون" },
    { category: "chat-sec", command: "pm", desc: "ترسل لشخص في الخاص" },
    { category: "chat-sec", command: "bind 1 chatbox", desc: "شات بوكس" },
    { category: "weapons-sec", command: "Makegun", desc: "صنع سلاح" },
    { category: "weapons-sec", command: "Makeammo", desc: "صنع رصاص" },
    { category: "weapons-sec", command: "gunlist / gunchart", desc: "معرفة معلومات عن السلاح" },
    { category: "weapons-sec", command: "gunmaker", desc: "فتح لوحة الأسلحة" },
    { category: "weapons-sec", command: "Disarm", desc: "حذف جميع أسلحة لاعب معين" },
    { category: "weapons-sec", command: "delitemsfromint", desc: "حذف سلاح من منزل" },
    { category: "giving-sec", command: "givesuperman", desc: "إعطاء طيران" },
    { category: "giving-sec", command: "setmoney", desc: "إعطاء أموال مرة واحدة" },
    { category: "giving-sec", command: "givemoney", desc: "إعطاء مال (كم تبي)" },
    { category: "giving-sec", command: "Givegc", desc: "إعطاء جي سي" },
    { category: "giving-sec", command: "Forcepayday", desc: "تزويد ساعات" },
    { category: "giving-sec", command: "Forcepaydayall", desc: "إعطاء يوم جديد لجميع اللاعبين" },
    { category: "giving-sec", command: "forcepayday", desc: "إعطاء يوم جديد للاعب معين" },
    { category: "giving-sec", command: "setskin", desc: "إعطاء شخصية" },
    { category: "giving-sec", command: "Setrace", desc: "تغيير بشرة اللاعب" },
    { category: "giving-sec", command: "agivelicense", desc: "إعطاء لاعب رخصة" },
    { category: "giving-sec", command: "atakelicense / takelicense", desc: "إلغاء رخصة / سحب رخصة شخص" },
    { category: "giving-sec", command: "setjob id 5", desc: "إعطاء رخصة ميكانيكي" },
    { category: "giving-sec", command: "Setjob", desc: "إعطاء لاعب وظيفة" },
    { category: "giving-sec", command: "deljob", desc: "حذف وظيفة لاعب" },
    { category: "giving-sec", command: "Revive", desc: "إنعاش شخص" },
    { category: "giving-sec", command: "sethp", desc: "قتل لاعب" },
    { category: "giving-sec", command: "Setarmor", desc: "إعطاء درع لشخص بنسبة" },
    { category: "giving-sec", command: "dellanguage", desc: "حذف لغة من شخص" },
    { category: "giving-sec", command: "setlanguage / setlang", desc: "إعطاء لغة لشخص" },
    { category: "basic-sec", command: "givesuperman", desc: "إعطاء طيران" },
    { category: "basic-sec", command: "Gotoplace", desc: "الانتقال إلى مكان (igs/bank/ls/lv/sf/ash/dmv/1str/sfpd/cityhall)" },
    { category: "basic-sec", command: "Places", desc: "معرفة اسم المكان" },
    { category: "basic-sec", command: "Goto", desc: "الانتقال إلى شخص" },
    { category: "basic-sec", command: "Gethere", desc: "سحب شخص" },
    { category: "basic-sec", command: "Sendto", desc: "إرسال شخص لشخص" },
    { category: "basic-sec", command: "Sendtoveh", desc: "إرسال شخص لسيارة" },
    { category: "basic-sec", command: "Enterveh", desc: "تركيب شخص في سيارة" },
    { category: "basic-sec", command: "Eject / eject", desc: "إنزال شخص من سيارة / إنزال شخص من سيارتك" },
    { category: "basic-sec", command: "Check", desc: "معلومات اللاعب" },
    { category: "basic-sec", command: "Findalts", desc: "معرفة كم شخصية في الحساب" },
    { category: "basic-sec", command: "Freeze", desc: "تجميد لاعب" },
    { category: "basic-sec", command: "Unfreeze", desc: "فك تجميد لاعب" },
    { category: "basic-sec", command: "Clearchat / clearchat", desc: "تنظيف ومسح الشات" },
    { category: "basic-sec", command: "Gotoveh", desc: "الانتقال إلى سيارة" },
    { category: "basic-sec", command: "Getveh", desc: "سحب سيارة" },
    { category: "basic-sec", command: "Sendveh", desc: "إرسال سيارة لشخص" },
    { category: "basic-sec", command: "Checkveh", desc: "معلومات السيارة" },
    { category: "basic-sec", command: "Fixveh", desc: "إصلاح سيارة" },
    { category: "basic-sec", command: "Fuelveh", desc: "إضافة بنزين" },
    { category: "basic-sec", command: "Flip", desc: "قلب سيارة" },
    { category: "basic-sec", command: "Unflip", desc: "تعديل السيارة" },
    { category: "basic-sec", command: "Respawnveh", desc: "رسبنة السيارات" },
    { category: "basic-sec", command: "Restoreveh", desc: "استرجاع سيارة محذوفة" },
    { category: "basic-sec", command: "Aunimpound", desc: "إزالة السيارة من الحجز" },
    { category: "basic-sec", command: "Adde", desc: "صنع سهم" },
    { category: "basic-sec", command: "Dele", desc: "حذف السهم" },
    { category: "basic-sec", command: "Fixnearbye", desc: "إصلاح أو استرجاع السهم" },
    { category: "basic-sec", command: "nearbye", desc: "معرفة إيدي السهم / إظهار أو إخفاء السهم" },
    { category: "basic-sec", command: "Rbs", desc: "وضع حاجز" },
    { category: "basic-sec", command: "Delrp", desc: "مسح الحاجز" },
    { category: "basic-sec", command: "Nearbyrb", desc: "معرفة إيدي الحاجز" },
    { category: "basic-sec", command: "Restock / restock", desc: "تعبئة محل / تعبئة البائعين في المحل" },
    { category: "basic-sec", command: "Freecam", desc: "اختراق الجدران" },
    { category: "basic-sec", command: "Auncuff", desc: "فك كلبش" },
    { category: "basic-sec", command: "Marry id id", desc: "تزويج شخصين" },
    { category: "basic-sec", command: "Setjob id 5", desc: "إعطاء رخصة ميكانيكي" },
    { category: "basic-sec", command: "Nearbyshops", desc: "معرفة إيدي البائع" },
    { category: "basic-sec", command: "Showfactions", desc: "مشاهدة جميع الفاكشنات" },
    { category: "basic-sec", command: "Showfeedbacks", desc: "مشاهدة التقييم" },
    { category: "basic-sec", command: "Seefar 250 / seefar 250", desc: "تخفيف الـ لاق" },
    { category: "reports-sec", command: "Ar", desc: "قبول ريبورت" },
    { category: "reports-sec", command: "Ri", desc: "قراءة ريبورت" },
    { category: "reports-sec", command: "Di", desc: "رفع ريبورت" },
    { category: "reports-sec", command: "Cr", desc: "قفل ريبورت" },
    { category: "reports-sec", command: "FR", desc: "إلغاء ريبورت من قبل إدمن" },
    { category: "reports-sec", command: "Showfeedbacks", desc: "مشاهدة التقييم" },
    { category: "reports-sec", command: "Getpoint / mypoints", desc: "معرفة نقاطك" },
    { category: "punish-sec", command: "Jail", desc: "سجن واحد" },
    { category: "punish-sec", command: "ojail", desc: "سجن لاعب بلا اتصال" },
    { category: "punish-sec", command: "Unjail", desc: "فك سجن" },
    { category: "punish-sec", command: "jailed", desc: "رؤية جميع المساجين" },
    { category: "punish-sec", command: "ck", desc: "إعطاء سي كي" },
    { category: "punish-sec", command: "cks", desc: "رؤية جميع السي كي" },
    { category: "punish-sec", command: "unck", desc: "فك السي كي" },
    { category: "punish-sec", command: "warn", desc: "إعطاء تحذير (3 تحذيرات = باند)" },
    { category: "punish-sec", command: "Pkick", desc: "طرد اللاعب" },
    { category: "punish-sec", command: "Slap", desc: "إعطاء سلاب" },
    { category: "punish-sec", command: "Bury", desc: "دفن لاعب" },
    { category: "punish-sec", command: "sjail", desc: "سجن لاعب بدون علم أحد (للإدمن فقط)" },
    { category: "punish-sec", command: "Skick", desc: "طرد لاعب بدون علم أحد (للإدمن فقط)" },
    { category: "punish-sec", command: "soban", desc: "باند لاعب بدون علم أحد (للإدمن فقط)" },
    { category: "punish-sec", command: "sojail", desc: "سجن لاعب بلا اتصال بدون علم أحد" },
    { category: "punish-sec", command: "showban", desc: "معرفة سبب الحظر" },
    { category: "punish-sec", command: "oban", desc: "حظر لاعب بلا اتصال" },
    { category: "punish-sec", command: "pban", desc: "حظر لاعب لمدة محددة" },
    { category: "punish-sec", command: "Unbind", desc: "فك باند" },
    { category: "punish-sec", command: "banaccount", desc: "باند لحساب معين" },
    { category: "punish-sec", command: "Findserial", desc: "معرفة سريال لاعب" },
    { category: "punish-sec", command: "banip [IP] [Reason]", desc: "باند أيبي" },
    { category: "punish-sec", command: "banserial [Serial] [Reason]", desc: "باند سريال" },
    { category: "general-sec", command: "quitjob", desc: "خروج من الوظيفة" },
    { category: "general-sec", command: "setvol", desc: "رفع صوت راديو السيارة" },
    { category: "general-sec", command: "glue", desc: "تثبيت اللاعب فوق الأشياء" },
    { category: "general-sec", command: "staff", desc: "رؤية الإداريين المتواجدين" },
    { category: "general-sec", command: "status", desc: "كتابة حالة فوق رأس اللاعب" },
    { category: "general-sec", command: "showchat", desc: "إخفاء/إظهار الشات" },
    { category: "general-sec", command: "writenote", desc: "كتابة نوته" },
    { category: "general-sec", command: "reconnect", desc: "إعادة تشغيل السيرفر" },
    { category: "general-sec", command: "ads", desc: "عمل إعلان" },
    { category: "general-sec", command: "texlist", desc: "إزالة الديكور من منزلك" },
    { category: "general-sec", command: "movesafe", desc: "تحريك خزنة" },
    { category: "general-sec", command: "gate", desc: "فتح بوابة" },
    { category: "general-sec", command: "history", desc: "إظهار الهوستري" },
    { category: "general-sec", command: "cup", desc: "حمل شخص" },
    { category: "general-sec", command: "cdw", desc: "إنزال شخص" },
    { category: "general-sec", command: "animselect / anims", desc: "جميع الحركات" },
    { category: "general-sec", command: "fp", desc: "منظور الشخص الأول" },
    { category: "leader-sec", command: "gov", desc: "عمل إعلان وظيفي" },
    { category: "leader-sec", command: "issuebadge", desc: "عمل شارة" },
    { category: "leader-sec", command: "togglef", desc: "قفل شات الوظيفة" },
    { category: "leader-sec", command: "f", desc: "شات الوظيفة" },
    { category: "leader-sec", command: "fl", desc: "شات الليدرات" },
    { category: "leader-sec", command: "hq", desc: "شات عام الوظيفة" },
    { category: "radio-sec", command: "tuneradio", desc: "دخول تردد راديو" },
    { category: "radio-sec", command: "toggleradio", desc: "قفل/تشغيل الراديو" },
    { category: "radio-sec", command: "rf", desc: "صنع أو حذف راديو لفاكشن" },
    { category: "radio-sec", command: "srd", desc: "قفل جميع راديو السيارات حولك" },
    { category: "radio-sec", command: "setvol 100", desc: "التحكم بدرجة صوت راديو السيارة" },
    { category: "ems-sec", command: "cpr", desc: "حركة إنعاش" },
    { category: "ems-sec", command: "mrevive", desc: "أمر إنعاش" },
    { category: "ems-sec", command: "heal 100", desc: "إعطاء دم" },
    { category: "ems-sec", command: "backup", desc: "عمل باك أب" },
    { category: "police-sec", command: "setwalk 62", desc: "مسك سلاح" },
    { category: "police-sec", command: "togattach", desc: "حمل السلاح على الصدر" },
    { category: "police-sec", command: "handsup", desc: "أمر الاستسلام" },
    { category: "police-sec", command: "gunup", desc: "أمر رفع السلاح على المجرم" },
    { category: "police-sec", command: "bat", desc: "ترفع السلاح" },
    { category: "police-sec", command: "ticket", desc: "إعطاء مخالفات" },
    { category: "police-sec", command: "takelicense", desc: "سحب رخصة شخص" },
    { category: "police-sec", command: "fingerprint", desc: "تشوف بصمة الشخص" },
    { category: "police-sec", command: "traffic", desc: "إظهار لوحات فوق السيارة" },
    { category: "police-sec", command: "n", desc: "تبديل وضعية السلاح" },
    { category: "police-sec", command: "mdc", desc: "قائمة البلاغات" },
    { category: "police-sec", command: "throwspikes", desc: "رمي الأشواك" },
    { category: "police-sec", command: "removespikes", desc: "حذف الأشواك" },
    { category: "police-sec", command: "togspeedcamera 120", desc: "أمر رادار السرعة" },
    { category: "press-sec", command: "interview", desc: "إعطاء ميك" },
    { category: "press-sec", command: "endinterview", desc: "أخذ الميك" },
    { category: "press-sec", command: "starttv", desc: "عمل بث مباشر" },
    { category: "press-sec", command: "endtv", desc: "إنهاء البث المباشر" },
    { category: "press-sec", command: "movetv", desc: "تحريك الكاميرا" },
    { category: "press-sec", command: "i", desc: "للتحدث" },
    { category: "court-sec", command: "changename", desc: "تغيير اسم" },
    { category: "court-sec", command: "marry", desc: "أمر زواج" },
    { category: "court-sec", command: "divorce", desc: "أمر طلاق" },
    { category: "airport-sec", command: "fuel", desc: "طلب تعبئة بنزين للطائرة" },
    { category: "airport-sec", command: "air", desc: "التحدث في الراديو الجوي" },
    { category: "airport-sec", command: "maps", desc: "رؤية تخطيط المطارات" },
    { category: "mechanic-sec", command: "towbike", desc: "سحب دراجة" },
    { category: "mechanic-sec", command: "veh", desc: "تصليح سيارة" },
    { category: "mechanic-sec", command: "Edveh", desc: "التعديل على السيارة" },
    { category: "teleport-sec", command: "Gotoplace", desc: "الانتقال إلى مكان (igs/bank/ls/lv/sf/ash/dmv/1str/sfpd/cityhall)" },
    { category: "teleport-sec", command: "goto", desc: "انتقال لشخص" },
    { category: "teleport-sec", command: "gotoveh", desc: "انتقال لسيارة" },
    { category: "teleport-sec", command: "gotomark", desc: "انتقال لمارك" },
    { category: "teleport-sec", command: "gotointi", desc: "انتقال داخل إنترو" },
    { category: "teleport-sec", command: "gotohouse / gotoint", desc: "انتقال لإنترو" },
    { category: "teleport-sec", command: "gotogate", desc: "انتقال لبوابة" },
    { category: "mode-sec", command: "startres", desc: "تشغيل مود" },
    { category: "mode-sec", command: "stopres", desc: "إيقاف مود" },
    { category: "mode-sec", command: "restartres", desc: "عمل ريستارت لمود" },
    { category: "mode-sec", command: "mods", desc: "إظهار مود السيارات" },
    { category: "pull-sec", command: "gethere", desc: "سحب شخص" },
    { category: "pull-sec", command: "getveh", desc: "سحب سيارة" },
    { category: "restart-sec", command: "restart bank", desc: "ريستارت البنك" },
    { category: "restart-sec", command: "restartres", desc: "ريستارت مود" },
    { category: "restart-sec", command: "restartcarshop / restartcarshops", desc: "ريستارت / رسبنة معرض السيارات" },
    { category: "restart-sec", command: "restartvehall", desc: "ريستارت جميع السيارات" },
    { category: "restart-sec", command: "resetaccount", desc: "ريستارت لحساب معين" },
    { category: "restart-sec", command: "restartresfaction-system", desc: "ريستارت فاكشن" },
    { category: "info-sec", command: "setage", desc: "تغيير عمر لاعب" },
    { category: "info-sec", command: "setdob", desc: "تغيير ميلاد لاعب" },
    { category: "info-sec", command: "setgender", desc: "تغيير جنس لاعب (ولد/بنت)" },
    { category: "info-sec", command: "setheight", desc: "تغيير وزن لاعب" },
    { category: "info-sec", command: "changename", desc: "تغيير اسم لاعب" }
];
