const serverRules = [
    { rule: "AR", desc: "استخدام الرتبة للمصلحة الشخصية (Aim Rank)" },
    { rule: "ATA", desc: "نقل ممتلكات شخصية إلى أخرى (alt to alt)" },
    { rule: "Arson", desc: "التسبب في حريق" },
    { rule: "AGC", desc: "استخدام القلتشات (Abusing Game/Script)" },
    { rule: "SK", desc: "قتل عند الرسبون أو المستشفى (Spawn Killing)" },
    { rule: "SC", desc: "استخدام اسم شخصية مشهورة" },
    { rule: "SL", desc: "حياة مقززة" },
    { rule: "SP", desc: "النصب بأكثر من 10 آلاف" },
    { rule: "SE", desc: "تخريب التوظيف" },
    { rule: "CK", desc: "موت شخصية أو إعدام" },
    { rule: "CR", desc: "الجري بدوران وإطلاق نار (Chicken Run)" },
    { rule: "CTV", desc: "لغة التهكير والبرمجة" },
    { rule: "CD", desc: "تطوير الشخصية (Character Development)" },
    { rule: "DM", desc: "القتل بدون سبب مقنع (Deathmatching)" },
    { rule: "DP", desc: "دعس شخص بدون أربي" },
    { rule: "DB", desc: "تصدم السيارات ودعس الأشخاص (Drive By)" },
    { rule: "DDP", desc: "القتل وأنت تسوق" },
    { rule: "DUC", desc: "تدمير شخصية (الانتحار)" },
    { rule: "Dos", desc: "ديوتي بدون شارة" },
    { rule: "RR", desc: "الجري دون تعب (Run Run)" },
    { rule: "RK", desc: "قتل الانتقام (Revenge Kill)" },
    { rule: "RTR", desc: "الجري دون تعب" },
    { rule: "RPZ", desc: "منطقة العيش في السيرفر (Role Play Zone)" },
    { rule: "RDM", desc: "قتل نفس الشخص بدون توقف" },
    { rule: "RPG", desc: "أخذ أربي جي من أمر السلاح وعليه وارن" },
    { rule: "MG", desc: "اختلاط الشات أو المعلومات (Meta Gaming)" },
    { rule: "MC", desc: "إطلاق نار بالغلط أو عمل شيء خطأ" },
    { rule: "MD", desc: "سوء استخدام الكلبشات" },
    { rule: "MA", desc: "تعدد الحسابات (Multiple Accounts)" },
    { rule: "LTA", desc: "الهروب من الأربي" },
    { rule: "Low-RP", desc: "استخدام أربي ضعيف" },
    { rule: "LK", desc: "تحتاج إذن لإطلاق نار في مكان عام" },
    { rule: "PG", desc: "تكون خارق الطبيعة (Power Gaming)" },
    { rule: "PK", desc: "فقدان الذاكرة بعد الموت" },
    { rule: "PD", desc: "استفزاز الشرطة بغرض المتعة" },
    { rule: "BH", desc: "الجري وأنت تقفز (Bonny Hopping)" },
    { rule: "BR", desc: "يجب القتل داخل الأربي فقط" },
    { rule: "BRAWLS", desc: "القتل بدون أربي" },
    { rule: "KOS", desc: "الحقد على لاعب أو إسناد لاعب" },
    { rule: "GR", desc: "احترام الناس (القاعدة الذهبية)" },
    { rule: "NG", desc: "سرقة سيارة شخص دون أربي" },
    { rule: "NK", desc: "تضرب شخص بيدك أو سلاح أبيض وأنت تجري (Ninja Kicking)" },
    { rule: "NJ", desc: "تنزل شخص من سيارته وتهرب (Ninja Jacking)" },
    { rule: "NONRP", desc: "فعل أشياء بدون أربي" },
    { rule: "TK", desc: "تقتل شخص من الفاكشن اللي أنت فيه" },
    { rule: "VDM", desc: "استخدام سيارة ودعس الأشخاص" },
    { rule: "WH", desc: "تركب موتسيكل وتقفز فوق الجبال والبيوت" },
    { rule: "UH", desc: "فعل العادات المضرة (التدخين أو تدمير الحياة الشخصية)" }
];
